version: 2
jobs:
  deploy_chart:
    working_directory: /workspace
    docker:
      - image: caryyu/helm-tools:latest
    steps:
      - checkout

      - run:
          name: Helm Build
          command: |
            mkdir /tmp/gitea
            cp -r * /tmp/gitea
            helm dependency build /tmp/gitea
            helm package /tmp/gitea

      - run:
          name: Clone Repository
          command: |
            git clone git@github.com:caryyu/helm-charts.git /tmp/helm-charts
            cd /tmp/helm-charts

      - run:
          name: Git Config
          command: |
            git config --global user.email "caryyu.tg@gmail.com"
            git config --global user.name "caryyu"

      - run:
          name: Deploy to Repository
          command: |
            mv /workspace/gitea*.tgz /tmp/helm-charts
            helm repo index .
            git add .
            git commit -m "updated by circleci"
            git push