apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
    app: {{ template "gitea.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gitea.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations: 
        checksum/configs: {{ include (print $.Template.BasePath "/configs.yaml") . | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "gitea.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        envFrom:
        - secretRef:
            name: gitea-init-secret
        volumeMounts:
        - mountPath: /data/gitea/conf/
          name: gitea-config
        - mountPath: /etc/gitea/conf/
          name: gitea-immutable-config
        - mountPath: /etc/gitea/scripts/
          name: gitea-init-scripts
        command: [ "sh", "/etc/gitea/scripts/init.sh" ]
      containers:
      - name: gitea
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 3000
        volumeMounts:
        - mountPath: /data/gitea/conf
          name: gitea-config
        - mountPath: /data/git/gitea-repositories
          name: gitea-repositories
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      volumes:
      - name: gitea-immutable-config
        configMap:
          name: gitea-immutable-config
      - name: gitea-init-scripts
        configMap:
          name: gitea-init-scripts
      - name: gitea-config
        emptyDir: {}
      - name: gitea-repositories
        persistentVolumeClaim:
         claimName: gitea-repositories-pvc