apiVersion: v1
kind: Secret
metadata:
  name: gitea-init-secret
  labels:
    app: {{ template "gitea.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.config.init.adminPassword -}}
  ADMIN_PASSWORD: {{ .Values.config.init.adminPassword | b64enc | quote }}
  {{ else -}}
  ADMIN_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end -}}
  ADMIN_USER: {{ .Values.config.init.adminUser | b64enc | quote }}
  ADMIN_EMAIL: {{ .Values.config.init.adminEmail | b64enc | quote }}

  {{ if .Values.config.init.authEnabled -}}
  AUTH_NAME: {{ .Values.config.init.authName | b64enc | quote }}
  AUTH_PROVIDER: {{ .Values.config.init.authProvider | b64enc | quote }}
  AUTH_KEY: {{ .Values.config.init.authKey | b64enc | quote }}
  AUTH_SECRET: {{ .Values.config.init.authSecret | b64enc | quote }}
  AUTH_AUTODISCOVER_URL: {{ .Values.config.init.authAutoDiscoverUrl | b64enc | quote }}
  {{ end -}}
