
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-init-scripts
  labels:
    app: {{ template "gitea.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "scripts/*.sh").AsConfig | indent 2 }}