apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "gitea.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  name: {{ template "gitea.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ template "gitea.name" . }}
    release: {{ .Release.Name }}
{{- range $key, $value := .Values.service.selector }}
    {{ $key }}: {{ $value | quote }}
{{- end }}